# Site settings
title: My Jekyll Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple Jekyll site built for learning and sharing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

# Social links (optional)
twitter_username: your_twitter
github_username: your_github
linkedin_username: your_linkedin

# Build settings
theme: minima # You can replace with any theme (e.g. jekyll-theme-cayman)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink: /:categories/:title/

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM

# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Collections (optional)
collections:
  posts:
    output: true

# Defaults (optional)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Excludes (optional)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Include (optional)
include:
  - _pages

# Deployment settings for GitHub Pages (if applicable)
# Uncomment if deploying to GitHub Pages
# remote_theme: pages-themes/cayman@v0.2.0

# Custom variables (optional)
author: Your Name
